[build]
builder = "dockerfile"
dockerfilePath = "apps/web/Dockerfile"
dockerContextPath = "."

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 30
